### ISSUE TITLE
Please convert the manual to rst

### ISSUE THREAD

**Issue by pcav** [SCrommelinck/BoundaryDelineation#2]
In this way it will be easier to translate, distribute, and improve.
Please follow QGIS formatting choices for coherence.
Thanks.

**Comment by SCrommelinck** [comment]
I moved the manual to the project website (https://its4land.com/automate-it-wp5/), as that one should not be considered as a final manual for QGIS users. I created that manual to explain the use of the plugin to a group of volunteers that tested it. Once the experimental phase is finished and the final structure of the plugin is decided, I will rewrite the manual and add it as a rst file. From my understanding GitHub is really to share code and a short explanation and the project website I provide more extensive explanations, a link to a YouTube video and so on. The plugin provides a large GUI, where each step is explained by the user. It is designed to be self-explanatory also without a manual.
